spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payroll-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      retries: 3
    properties:
      allow.auto.create.topics: true

      
    topics:
      hrms:
        partitions:4
        replicas:2