spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payroll-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 3
    properties:
      auto.create.topics.enable: true   

  
        
kafka:
  topics:
    hrms:
      partitions: 4
      replicas: 2
        
        